# Generated by Django 3.0.3 on 2020-04-04 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Hanging Out', max_length=15)),
                ('subject', models.CharField(default='School Work', max_length=150)),
                ('geodata', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
